apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: simple-server
        image: docker.artifactory.euw.platformservices.io/miv01/simple-server:1.0
