kind: Pod
apiVersion: v1
metadata:
  name: simple-server
  namespace: kube-public
  labels:
    tier: frontend
spec:
  containers:
    - name: simple-server
      image: mihaitaivli/simple_server:1.0
